on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      python-module:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true


jobs:
  create-python-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Install project dependencies
        run: pip install .

      - id: release
        uses: cdubos-fr/tag-python-project@main
        with:
          python-version: "${{ inputs.python-version }}"
          python-module: "${{ inputs.python-module }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
