on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: number


jobs:
  python-ci:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: {{ inputs.python-version }}

      - name: Install tox dependencies
        run: pip install tox-gh

      - name: Setup tests suites
        run: tox -vv --notest

      - name: Run test suite
        run: tox --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
